---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ktr8om71x5az/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp contact.php $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R unisoft $DEPLOYPATH
    - /bin/cp -R HR $DEPLOYPATH
    - /bin/cp -R shop $DEPLOYPATH
