<?php
// Initialize the session
session_start();
 
// Check if the user is logged in, if not then redirect him to login page
if(!isset($_SESSION["loggedin"]) || $_SESSION["loggedin"] !== true){
    header("location: login.php");
    exit;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="assests/styles.css">
    <title>Add Plan</title>
</head>
<body class="bg-dark text-warning">
    <?php 
        require_once('./includes/config.php');
    ?>
    <?php
    include('navbar.php');
    ?>
    <div class="container mt-5">
        <div class="row mt-5">
            <div class="col-md-6">
                <h1>Create Production Plan</h1>
            </div>
            <div class="col-md-6 d-flex justify-content-end">
                <a href="show-plan.php"><button class="btn btn-info">Go to See All</button></a>
            </div>
        </div>
        <form action="./includes/add-data.inc.php" method="post" class="form-group">
            <div class="row mt-5">
                <div class="col-md-5">
                    <label for="article">Select Article</label>
                    <br>
                    <input type="text" list="article-data" name="article" id="article" class="form-control inp">

                        <datalist id="article-data">
                    <?php
                        $stmt = "SELECT article_name FROM data";
                    $result = $conn->query($stmt);

                        if ($result->num_rows > 0) {
                            // output data of each row
                            while($row = $result->fetch_assoc()) {
                                echo "<option value='" . $row['article_name'] . "'>" . $row['article_name'] . "</option>";
                            }
                          }
                        ?>
                    </datalist>
                </div>
                <div class="col-md-2">
                    <label for="">Select size</label>
                    <br>
                    <input type="text" name="size" id="size" list="size-data" class="form-control inp">
                    <datalist id="size-data">
                        <?php
                        $stmt = "SELECT size FROM data";
                        $result = $conn->query($stmt);

                        if ($result->num_rows > 0) {
                            // output data of each row
                            while($row = $result->fetch_assoc()) {
                                echo "<option value='" . $row['size'] . "'>" . $row['size'] . "</option>";
                            }
                          }
                        ?>
                    </datalist>
                </div>
                <div class="col-md-5">
                    <label for="">Color</label>
                    <br>
                    <input type="text" name="color" id="color" class="form-control inp">
                    <br>
                </div>
            </div>
            <div class="row">
                <div class="col-md-5">
                    <label for="">Plan No.</label>
                    <br>
                    <input type="text" name="plan" id="plan" class="form-control inp" maxlength="3">
                </div>
                <div class="col-md-2">
                    <!-- <label for=">Lot From</label>
                    <br>
                    <select class="custom-select inp">
                        <option value=""></option>
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                        <option>6</option>
                        <option>7</option>
                        <option>8</option>
                        <option>9</option>
                        <option>10</option>
                        <option>11</option>
                        <option>12</option>
                        <option>13</option>
                        <option>14</option>
                        <option>15</option>
                        <option>16</option>
                        <option>17</option>
                        <option>18</option>
                        <option>19</option>
                        <option>20</option>
                        <option>21</option>
                        <option>22</option>
                        <option>23</option>
                        <option>24</option>
                        <option>25</option>
                        <option>26</option>
                        <option>27</option>
                        <option>28</option>
                        <option>29</option>
                        <option>30</option>
                        <option>31</option>
                        <option>32</option>
                        <option>33</option>
                        <option>34</option>
                        <option>35</option>
                        <option>36</option>
                        <option>37</option>
                        <option>38</option>
                        <option>39</option>
                        <option>40</option>
                        <option>41</option>
                        <option>42</option>
                        <option>43</option>
                        <option>44</option>
                        <option>45</option>
                        <option>46</option>
                        <option>47</option>
                        <option>48</option>
                        <option>49</option>
                        <option>50</option>
                        <option>51</option>
                        <option>52</option>
                        <option>53</option>
                        <option>54</option>
                        <option>55</option>
                        <option>56</option>
                        <option>57</option>
                        <option>58</option>
                        <option>59</option>
                        <option>60</option>
                        <option>61</option>
                        <option>62</option>
                        <option>63</option>
                        <option>64</option>
                        <option>65</option>
                        <option>66</option>
                        <option>67</option>
                        <option>68</option>
                        <option>69</option>
                        <option>70</option>
                        <option>71</option>
                        <option>72</option>
                        <option>73</option>
                        <option>74</option>
                        <option>75</option>
                        <option>76</option>
                        <option>77</option>
                        <option>78</option>
                        <option>79</option>
                        <option>80</option>
                        <option>81</option>
                        <option>82</option>
                        <option>83</option>
                        <option>84</option>
                        <option>85</option>
                        <option>86</option>
                        <option>87</option>
                        <option>88</option>
                        <option>89</option>
                        <option>90</option>
                        <option>91</option>
                        <option>92</option>
                        <option>93</option>
                        <option>94</option>
                        <option>95</option>
                        <option>96</option>
                        <option>97</option>
                        <option>98</option>
                        <option>99</option>
                        <option>100</option>
                        <option>101</option>
                        <option>102</option>
                        <option>103</option>
                        <option>104</option>
                        <option>105</option>
                        <option>106</option>
                        <option>107</option>
                        <option>108</option>
                        <option>109</option>
                        <option>110</option>
                        <option>111</option>
                        <option>112</option>
                        <option>113</option>
                        <option>114</option>
                        <option>115</option>
                        <option>116</option>
                        <option>117</option>
                        <option>118</option>
                        <option>119</option>
                        <option>120</option>
                        <option>121</option>
                        <option>122</option>
                        <option>123</option>
                        <option>124</option>
                        <option>125</option>
                        <option>126</option>
                        <option>127</option>
                        <option>128</option>
                        <option>129</option>
                        <option>130</option>
                        <option>131</option>
                        <option>132</option>
                        <option>133</option>
                        <option>134</option>
                        <option>135</option>
                        <option>136</option>
                        <option>137</option>
                        <option>138</option>
                        <option>139</option>
                        <option>140</option>
                        <option>141</option>
                        <option>142</option>
                        <option>143</option>
                        <option>144</option>
                        <option>145</option>
                        <option>146</option>
                        <option>147</option>
                        <option>148</option>
                        <option>149</option>
                        <option>150</option>
                        <option>151</option>
                        <option>152</option>
                        <option>153</option>
                        <option>154</option>
                        <option>155</option>
                        <option>156</option>
                        <option>157</option>
                        <option>158</option>
                        <option>159</option>
                        <option>160</option>
                        <option>161</option>
                        <option>162</option>
                        <option>163</option>
                        <option>164</option>
                        <option>165</option>
                        <option>166</option>
                        <option>167</option>
                        <option>168</option>
                        <option>169</option>
                        <option>170</option>
                        <option>171</option>
                        <option>172</option>
                        <option>173</option>
                        <option>174</option>
                        <option>175</option>
                        <option>176</option>
                        <option>177</option>
                        <option>178</option>
                        <option>179</option>
                        <option>180</option>
                        <option>181</option>
                        <option>182</option>
                        <option>183</option>
                        <option>184</option>
                        <option>185</option>
                        <option>186</option>
                        <option>187</option>
                        <option>188</option>
                        <option>189</option>
                        <option>190</option>
                        <option>191</option>
                        <option>192</option>
                        <option>193</option>
                        <option>194</option>
                        <option>195</option>
                        <option>196</option>
                        <option>197</option>
                        <option>198</option>
                        <option>199</option>
                        <option>200</option>
                        <option>201</option>
                        <option>202</option>
                        <option>203</option>
                        <option>204</option>
                        <option>205</option>
                        <option>206</option>
                        <option>207</option>
                        <option>208</option>
                        <option>209</option>
                        <option>210</option>
                        <option>211</option>
                        <option>212</option>
                        <option>213</option>
                        <option>214</option>
                        <option>215</option>
                        <option>216</option>
                        <option>217</option>
                        <option>218</option>
                        <option>219</option>
                        <option>220</option>
                        <option>221</option>
                        <option>222</option>
                        <option>223</option>
                        <option>224</option>
                        <option>225</option>
                        <option>226</option>
                        <option>227</option>
                        <option>228</option>
                        <option>229</option>
                        <option>230</option>
                        <option>231</option>
                        <option>232</option>
                        <option>233</option>
                        <option>234</option>
                        <option>235</option>
                        <option>236</option>
                        <option>237</option>
                        <option>238</option>
                        <option>239</option>
                        <option>240</option>
                        <option>241</option>
                        <option>242</option>
                        <option>243</option>
                        <option>244</option>
                        <option>245</option>
                        <option>246</option>
                        <option>247</option>
                        <option>248</option>
                        <option>249</option>
                        <option>250</option>
                        <option>251</option>
                        <option>252</option>
                        <option>253</option>
                        <option>254</option>
                        <option>255</option>
                        <option>256</option>
                        <option>257</option>
                        <option>258</option>
                        <option>259</option>
                        <option>260</option>
                        <option>261</option>
                        <option>262</option>
                        <option>263</option>
                        <option>264</option>
                        <option>265</option>
                        <option>266</option>
                        <option>267</option>
                        <option>268</option>
                        <option>269</option>
                        <option>270</option>
                        <option>271</option>
                        <option>272</option>
                        <option>273</option>
                        <option>274</option>
                        <option>275</option>
                        <option>276</option>
                        <option>277</option>
                        <option>278</option>
                        <option>279</option>
                        <option>280</option>
                        <option>281</option>
                        <option>282</option>
                        <option>283</option>
                        <option>284</option>
                        <option>285</option>
                        <option>286</option>
                        <option>287</option>
                        <option>288</option>
                        <option>289</option>
                        <option>290</option>
                        <option>291</option>
                        <option>292</option>
                        <option>293</option>
                        <option>294</option>
                        <option>295</option>
                        <option>296</option>
                        <option>297</option>
                        <option>298</option>
                        <option>299</option>
                        <option>300</option>
                        <option>301</option>
                        <option>302</option>
                        <option>303</option>
                        <option>304</option>
                        <option>305</option>
                        <option>306</option>
                        <option>307</option>
                        <option>308</option>
                        <option>309</option>
                        <option>310</option>
                        <option>311</option>
                        <option>312</option>
                        <option>313</option>
                        <option>314</option>
                        <option>315</option>
                        <option>316</option>
                        <option>317</option>
                        <option>318</option>
                        <option>319</option>
                        <option>320</option>
                        <option>321</option>
                        <option>322</option>
                        <option>323</option>
                        <option>324</option>
                        <option>325</option>
                        <option>326</option>
                        <option>327</option>
                        <option>328</option>
                        <option>329</option>
                        <option>330</option>
                        <option>331</option>
                        <option>332</option>
                        <option>333</option>
                        <option>334</option>
                        <option>335</option>
                        <option>336</option>
                        <option>337</option>
                        <option>338</option>
                        <option>339</option>
                        <option>340</option>
                        <option>341</option>
                        <option>342</option>
                        <option>343</option>
                        <option>344</option>
                        <option>345</option>
                        <option>346</option>
                        <option>347</option>
                        <option>348</option>
                        <option>349</option>
                        <option>350</option>
                        <option>351</option>
                        <option>352</option>
                        <option>353</option>
                        <option>354</option>
                        <option>355</option>
                        <option>356</option>
                        <option>357</option>
                        <option>358</option>
                        <option>359</option>
                        <option>360</option>
                        <option>361</option>
                        <option>362</option>
                        <option>363</option>
                        <option>364</option>
                        <option>365</option>
                        <option>366</option>
                        <option>367</option>
                        <option>368</option>
                        <option>369</option>
                        <option>370</option>
                        <option>371</option>
                        <option>372</option>
                        <option>373</option>
                        <option>374</option>
                        <option>375</option>
                        <option>376</option>
                        <option>377</option>
                        <option>378</option>
                        <option>379</option>
                        <option>380</option>
                        <option>381</option>
                        <option>382</option>
                        <option>383</option>
                        <option>384</option>
                        <option>385</option>
                        <option>386</option>
                        <option>387</option>
                        <option>388</option>
                        <option>389</option>
                        <option>390</option>
                        <option>391</option>
                        <option>392</option>
                        <option>393</option>
                        <option>394</option>
                        <option>395</option>
                        <option>396</option>
                        <option>397</option>
                        <option>398</option>
                        <option>399</option>
                        <option>400</option>
                        <option>401</option>
                        <option>402</option>
                        <option>403</option>
                        <option>404</option>
                        <option>405</option>
                        <option>406</option>
                        <option>407</option>
                        <option>408</option>
                        <option>409</option>
                        <option>410</option>
                        <option>411</option>
                        <option>412</option>
                        <option>413</option>
                        <option>414</option>
                        <option>415</option>
                        <option>416</option>
                        <option>417</option>
                        <option>418</option>
                        <option>419</option>
                        <option>420</option>
                        <option>421</option>
                        <option>422</option>
                        <option>423</option>
                        <option>424</option>
                        <option>425</option>
                        <option>426</option>
                        <option>427</option>
                        <option>428</option>
                        <option>429</option>
                        <option>430</option>
                        <option>431</option>
                        <option>432</option>
                        <option>433</option>
                        <option>434</option>
                        <option>435</option>
                        <option>436</option>
                        <option>437</option>
                        <option>438</option>
                        <option>439</option>
                        <option>440</option>
                        <option>441</option>
                        <option>442</option>
                        <option>443</option>
                        <option>444</option>
                        <option>445</option>
                        <option>446</option>
                        <option>447</option>
                        <option>448</option>
                        <option>449</option>
                        <option>450</option>
                        <option>451</option>
                        <option>452</option>
                        <option>453</option>
                        <option>454</option>
                        <option>455</option>
                        <option>456</option>
                        <option>457</option>
                        <option>458</option>
                        <option>459</option>
                        <option>460</option>
                        <option>461</option>
                        <option>462</option>
                        <option>463</option>
                        <option>464</option>
                        <option>465</option>
                        <option>466</option>
                        <option>467</option>
                        <option>468</option>
                        <option>469</option>
                        <option>470</option>
                        <option>471</option>
                        <option>472</option>
                        <option>473</option>
                        <option>474</option>
                        <option>475</option>
                        <option>476</option>
                        <option>477</option>
                        <option>478</option>
                        <option>479</option>
                        <option>480</option>
                        <option>481</option>
                        <option>482</option>
                        <option>483</option>
                        <option>484</option>
                        <option>485</option>
                        <option>486</option>
                        <option>487</option>
                        <option>488</option>
                        <option>489</option>
                        <option>490</option>
                        <option>491</option>
                        <option>492</option>
                        <option>493</option>
                        <option>494</option>
                        <option>495</option>
                        <option>496</option>
                        <option>497</option>
                        <option>498</option>
                        <option>499</option>
                        <option>500</option>
                        
                    </select> -->
                    <label for="">Lot No.</label>
                    <br>
                    <input type="text" name="lot" id="lot" class="form-control inp" maxlength="3">
                </div>
                <div class="col-md-2">
                    <!-- <label for=">Lot To</label>
                    <br>
                    <select class="custom-select inp">
                        <option value=""></option>
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                        <option>6</option>
                        <option>7</option>
                        <option>8</option>
                        <option>9</option>
                        <option>10</option>
                        <option>11</option>
                        <option>12</option>
                        <option>13</option>
                        <option>14</option>
                        <option>15</option>
                        <option>16</option>
                        <option>17</option>
                        <option>18</option>
                        <option>19</option>
                        <option>20</option>
                        <option>21</option>
                        <option>22</option>
                        <option>23</option>
                        <option>24</option>
                        <option>25</option>
                        <option>26</option>
                        <option>27</option>
                        <option>28</option>
                        <option>29</option>
                        <option>30</option>
                        <option>31</option>
                        <option>32</option>
                        <option>33</option>
                        <option>34</option>
                        <option>35</option>
                        <option>36</option>
                        <option>37</option>
                        <option>38</option>
                        <option>39</option>
                        <option>40</option>
                        <option>41</option>
                        <option>42</option>
                        <option>43</option>
                        <option>44</option>
                        <option>45</option>
                        <option>46</option>
                        <option>47</option>
                        <option>48</option>
                        <option>49</option>
                        <option>50</option>
                        <option>51</option>
                        <option>52</option>
                        <option>53</option>
                        <option>54</option>
                        <option>55</option>
                        <option>56</option>
                        <option>57</option>
                        <option>58</option>
                        <option>59</option>
                        <option>60</option>
                        <option>61</option>
                        <option>62</option>
                        <option>63</option>
                        <option>64</option>
                        <option>65</option>
                        <option>66</option>
                        <option>67</option>
                        <option>68</option>
                        <option>69</option>
                        <option>70</option>
                        <option>71</option>
                        <option>72</option>
                        <option>73</option>
                        <option>74</option>
                        <option>75</option>
                        <option>76</option>
                        <option>77</option>
                        <option>78</option>
                        <option>79</option>
                        <option>80</option>
                        <option>81</option>
                        <option>82</option>
                        <option>83</option>
                        <option>84</option>
                        <option>85</option>
                        <option>86</option>
                        <option>87</option>
                        <option>88</option>
                        <option>89</option>
                        <option>90</option>
                        <option>91</option>
                        <option>92</option>
                        <option>93</option>
                        <option>94</option>
                        <option>95</option>
                        <option>96</option>
                        <option>97</option>
                        <option>98</option>
                        <option>99</option>
                        <option>100</option>
                        <option>101</option>
                        <option>102</option>
                        <option>103</option>
                        <option>104</option>
                        <option>105</option>
                        <option>106</option>
                        <option>107</option>
                        <option>108</option>
                        <option>109</option>
                        <option>110</option>
                        <option>111</option>
                        <option>112</option>
                        <option>113</option>
                        <option>114</option>
                        <option>115</option>
                        <option>116</option>
                        <option>117</option>
                        <option>118</option>
                        <option>119</option>
                        <option>120</option>
                        <option>121</option>
                        <option>122</option>
                        <option>123</option>
                        <option>124</option>
                        <option>125</option>
                        <option>126</option>
                        <option>127</option>
                        <option>128</option>
                        <option>129</option>
                        <option>130</option>
                        <option>131</option>
                        <option>132</option>
                        <option>133</option>
                        <option>134</option>
                        <option>135</option>
                        <option>136</option>
                        <option>137</option>
                        <option>138</option>
                        <option>139</option>
                        <option>140</option>
                        <option>141</option>
                        <option>142</option>
                        <option>143</option>
                        <option>144</option>
                        <option>145</option>
                        <option>146</option>
                        <option>147</option>
                        <option>148</option>
                        <option>149</option>
                        <option>150</option>
                        <option>151</option>
                        <option>152</option>
                        <option>153</option>
                        <option>154</option>
                        <option>155</option>
                        <option>156</option>
                        <option>157</option>
                        <option>158</option>
                        <option>159</option>
                        <option>160</option>
                        <option>161</option>
                        <option>162</option>
                        <option>163</option>
                        <option>164</option>
                        <option>165</option>
                        <option>166</option>
                        <option>167</option>
                        <option>168</option>
                        <option>169</option>
                        <option>170</option>
                        <option>171</option>
                        <option>172</option>
                        <option>173</option>
                        <option>174</option>
                        <option>175</option>
                        <option>176</option>
                        <option>177</option>
                        <option>178</option>
                        <option>179</option>
                        <option>180</option>
                        <option>181</option>
                        <option>182</option>
                        <option>183</option>
                        <option>184</option>
                        <option>185</option>
                        <option>186</option>
                        <option>187</option>
                        <option>188</option>
                        <option>189</option>
                        <option>190</option>
                        <option>191</option>
                        <option>192</option>
                        <option>193</option>
                        <option>194</option>
                        <option>195</option>
                        <option>196</option>
                        <option>197</option>
                        <option>198</option>
                        <option>199</option>
                        <option>200</option>
                        <option>201</option>
                        <option>202</option>
                        <option>203</option>
                        <option>204</option>
                        <option>205</option>
                        <option>206</option>
                        <option>207</option>
                        <option>208</option>
                        <option>209</option>
                        <option>210</option>
                        <option>211</option>
                        <option>212</option>
                        <option>213</option>
                        <option>214</option>
                        <option>215</option>
                        <option>216</option>
                        <option>217</option>
                        <option>218</option>
                        <option>219</option>
                        <option>220</option>
                        <option>221</option>
                        <option>222</option>
                        <option>223</option>
                        <option>224</option>
                        <option>225</option>
                        <option>226</option>
                        <option>227</option>
                        <option>228</option>
                        <option>229</option>
                        <option>230</option>
                        <option>231</option>
                        <option>232</option>
                        <option>233</option>
                        <option>234</option>
                        <option>235</option>
                        <option>236</option>
                        <option>237</option>
                        <option>238</option>
                        <option>239</option>
                        <option>240</option>
                        <option>241</option>
                        <option>242</option>
                        <option>243</option>
                        <option>244</option>
                        <option>245</option>
                        <option>246</option>
                        <option>247</option>
                        <option>248</option>
                        <option>249</option>
                        <option>250</option>
                        <option>251</option>
                        <option>252</option>
                        <option>253</option>
                        <option>254</option>
                        <option>255</option>
                        <option>256</option>
                        <option>257</option>
                        <option>258</option>
                        <option>259</option>
                        <option>260</option>
                        <option>261</option>
                        <option>262</option>
                        <option>263</option>
                        <option>264</option>
                        <option>265</option>
                        <option>266</option>
                        <option>267</option>
                        <option>268</option>
                        <option>269</option>
                        <option>270</option>
                        <option>271</option>
                        <option>272</option>
                        <option>273</option>
                        <option>274</option>
                        <option>275</option>
                        <option>276</option>
                        <option>277</option>
                        <option>278</option>
                        <option>279</option>
                        <option>280</option>
                        <option>281</option>
                        <option>282</option>
                        <option>283</option>
                        <option>284</option>
                        <option>285</option>
                        <option>286</option>
                        <option>287</option>
                        <option>288</option>
                        <option>289</option>
                        <option>290</option>
                        <option>291</option>
                        <option>292</option>
                        <option>293</option>
                        <option>294</option>
                        <option>295</option>
                        <option>296</option>
                        <option>297</option>
                        <option>298</option>
                        <option>299</option>
                        <option>300</option>
                        <option>301</option>
                        <option>302</option>
                        <option>303</option>
                        <option>304</option>
                        <option>305</option>
                        <option>306</option>
                        <option>307</option>
                        <option>308</option>
                        <option>309</option>
                        <option>310</option>
                        <option>311</option>
                        <option>312</option>
                        <option>313</option>
                        <option>314</option>
                        <option>315</option>
                        <option>316</option>
                        <option>317</option>
                        <option>318</option>
                        <option>319</option>
                        <option>320</option>
                        <option>321</option>
                        <option>322</option>
                        <option>323</option>
                        <option>324</option>
                        <option>325</option>
                        <option>326</option>
                        <option>327</option>
                        <option>328</option>
                        <option>329</option>
                        <option>330</option>
                        <option>331</option>
                        <option>332</option>
                        <option>333</option>
                        <option>334</option>
                        <option>335</option>
                        <option>336</option>
                        <option>337</option>
                        <option>338</option>
                        <option>339</option>
                        <option>340</option>
                        <option>341</option>
                        <option>342</option>
                        <option>343</option>
                        <option>344</option>
                        <option>345</option>
                        <option>346</option>
                        <option>347</option>
                        <option>348</option>
                        <option>349</option>
                        <option>350</option>
                        <option>351</option>
                        <option>352</option>
                        <option>353</option>
                        <option>354</option>
                        <option>355</option>
                        <option>356</option>
                        <option>357</option>
                        <option>358</option>
                        <option>359</option>
                        <option>360</option>
                        <option>361</option>
                        <option>362</option>
                        <option>363</option>
                        <option>364</option>
                        <option>365</option>
                        <option>366</option>
                        <option>367</option>
                        <option>368</option>
                        <option>369</option>
                        <option>370</option>
                        <option>371</option>
                        <option>372</option>
                        <option>373</option>
                        <option>374</option>
                        <option>375</option>
                        <option>376</option>
                        <option>377</option>
                        <option>378</option>
                        <option>379</option>
                        <option>380</option>
                        <option>381</option>
                        <option>382</option>
                        <option>383</option>
                        <option>384</option>
                        <option>385</option>
                        <option>386</option>
                        <option>387</option>
                        <option>388</option>
                        <option>389</option>
                        <option>390</option>
                        <option>391</option>
                        <option>392</option>
                        <option>393</option>
                        <option>394</option>
                        <option>395</option>
                        <option>396</option>
                        <option>397</option>
                        <option>398</option>
                        <option>399</option>
                        <option>400</option>
                        <option>401</option>
                        <option>402</option>
                        <option>403</option>
                        <option>404</option>
                        <option>405</option>
                        <option>406</option>
                        <option>407</option>
                        <option>408</option>
                        <option>409</option>
                        <option>410</option>
                        <option>411</option>
                        <option>412</option>
                        <option>413</option>
                        <option>414</option>
                        <option>415</option>
                        <option>416</option>
                        <option>417</option>
                        <option>418</option>
                        <option>419</option>
                        <option>420</option>
                        <option>421</option>
                        <option>422</option>
                        <option>423</option>
                        <option>424</option>
                        <option>425</option>
                        <option>426</option>
                        <option>427</option>
                        <option>428</option>
                        <option>429</option>
                        <option>430</option>
                        <option>431</option>
                        <option>432</option>
                        <option>433</option>
                        <option>434</option>
                        <option>435</option>
                        <option>436</option>
                        <option>437</option>
                        <option>438</option>
                        <option>439</option>
                        <option>440</option>
                        <option>441</option>
                        <option>442</option>
                        <option>443</option>
                        <option>444</option>
                        <option>445</option>
                        <option>446</option>
                        <option>447</option>
                        <option>448</option>
                        <option>449</option>
                        <option>450</option>
                        <option>451</option>
                        <option>452</option>
                        <option>453</option>
                        <option>454</option>
                        <option>455</option>
                        <option>456</option>
                        <option>457</option>
                        <option>458</option>
                        <option>459</option>
                        <option>460</option>
                        <option>461</option>
                        <option>462</option>
                        <option>463</option>
                        <option>464</option>
                        <option>465</option>
                        <option>466</option>
                        <option>467</option>
                        <option>468</option>
                        <option>469</option>
                        <option>470</option>
                        <option>471</option>
                        <option>472</option>
                        <option>473</option>
                        <option>474</option>
                        <option>475</option>
                        <option>476</option>
                        <option>477</option>
                        <option>478</option>
                        <option>479</option>
                        <option>480</option>
                        <option>481</option>
                        <option>482</option>
                        <option>483</option>
                        <option>484</option>
                        <option>485</option>
                        <option>486</option>
                        <option>487</option>
                        <option>488</option>
                        <option>489</option>
                        <option>490</option>
                        <option>491</option>
                        <option>492</option>
                        <option>493</option>
                        <option>494</option>
                        <option>495</option>
                        <option>496</option>
                        <option>497</option>
                        <option>498</option>
                        <option>499</option>
                        <option>500</option>
                    </select> -->
                </div>
                <div class="col-md-3">
                    <label for="">Pairs</label>
                    <br>
                    <input type="text" name="pairs" id="pairs" class="form-control inp">
                    <br>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <input type="radio" name="radio" value="Timber Market" onclick="check2()" required> <label for="">Timber Market</label>
                </div>
                <div class="col-md-3">
                    <input type="radio" name="radio" value="DELUX Shoes" onclick="check2()" required> <label for="">DELUX Shoes</label>
                </div>
                <div class="col-md-3">
                    <input type="radio" name="radio" value="Factory Stock" onclick="check2()" required> <label for="">Factory Stock</label>
                </div>
                <div class="col-md-3">
                    <input type="radio" name="radio" value="Samples" onclick="check2()" required> <label for="">Samples</label>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <input type="radio" name="radio" value="other" onclick="check()" id="other" required> <label for="">Other</label>
                    <br>
                    <input type="text" name="other-text"id="other-text" class="form-control">
                </div>
                <div class="col-md-5 d-flex align-items-center justify-content-end">
                    <input type="submit" value="Submit" class="sub btn btn-success">
                </div>
            </div>
        </form>
    </div>
    
    <script>

        function check()
        {
            if (document.getElementById("other").checked == true)
            {
                document.getElementById("other-text").disabled = false;
            }
            
        }
        function check2()
        {
            document.getElementById("other-text").disabled = true;
        }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>